### ISSUE TITLE
TYPO3 12.x Update?

### ISSUE THREAD

**Issue by ingeniumdesign** [jweiland-net/indexnow#10]
Hi, can you provide the extension also for TYPO3 version 12? Thanks

**Comment by jweiland** [comment]
Yes, we will update the extension for v12, but this might take some time. 
v12 has not yet been released and there are some other extensions that have higher priority for an upgrade.
However, if you need an update soon, you may want to sponsor it to get the prio higher.

**Comment by helmut-winkelbach** [comment]
Any idea of a release date for TYPO3 version 12?

**Comment by srchild** [comment]
TYPO3 13.4 LTS is out now...

I'm thinking that a quick dirty hack might be a cron job which checks the xml sitemap(s) every 6-8 hours and submits the URLs for any pages with lastmod > time of last scheduled cron job. But a proper TYPO3 solution would obviously be better.

**Comment by sfroemkenjw** [comment]
I have released a TYPO3 12 compatible version, yesterday. And today I released a compatible version for TYPO3 13.

**Comment by srchild** [comment]
Thank you
