### ISSUE TITLE
[FEATURE] Handling of custom doktypes / pages

### ISSUE THREAD

**Issue by ayacoo** [jweiland-net/indexnow#5]
It should be possible to exclude doctypes from indexing to save resources. This can be either automated or additionally via a TypoScript constant, if you have generated your own doctypes.

**Comment by sfroemkenjw** [comment]
Hi @ayacoo 

version 0.0.4 now respects the usage of `pages:no_index`. Maybe that would be an option for you. Further I have added an event, where you can return page UID `0` to tell indexnow to prevent informing indexnow about updates.

Stefan
